variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  PORT: 8081

cache:
  paths:
  - .m2/repository

stages:
- build-and-deploy

maven-build:
  image: maven:3-jdk-8
  stage: build-and-deploy
  script:
  - "mvn clean install deploy -B --settings .m2/settings.xml"
  only:
  - master
  artifacts:
    paths:
    - target/*.jar